### ISSUE TITLE
Failed startup

### ISSUE THREAD

**Issue by odwrotnie** [graphqlize/graphqlize-demo#7]
While running this example you get

`Error scanning entry org/graphqlize/java/GraphQLResolver.class`

```
[success] Total time: 126 s (02:06), completed Nov 17, 2020 8:42:48 PM
sbt:Scalatra GraphQLize Demo Web App> 2020-11-17 20:42:48.486:INFO::main: Logging initialized @302ms to org.eclipse.jetty.util.log.StdErrLog
2020-11-17 20:42:48.507:INFO:oejr.Runner:main: Runner
2020-11-17 20:42:48.717:INFO:oejs.Server:main: jetty-9.4.8.v20171121, build timestamp: 2017-11-21T21:27:37Z, git hash: 82b8fb23f757335bb3329d540ce37a2a2615f0a8
2020-11-17 20:42:49.154:WARN:oeja.AnnotationParser:main: Unrecognized runtime asm version, assuming 393216
2020-11-17 20:42:50.832:INFO:oeja.AnnotationConfiguration:main: Scanning elapsed time=1676ms
2020-11-17 20:42:50.833:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@3ac42916{/,file:///app/target/webapp/,UNAVAILABLE}{file:///app/target/webapp/}
MultiException[java.lang.RuntimeException: Error scanning entry org/graphqlize/java/GraphQLResolver.class from jar file:///app/target/webapp/WEB-INF/lib/graphqlize-java-0.1.0-alpha20.jar, java.lang.RuntimeException: Error scanning entry org/graphqlize/java/GraphQLizeResolver.class from jar file:///app/target/webapp/WEB-INF/lib/graphqlize-java-0.1.0-alpha20.jar]
	at org.eclipse.jetty.annotations.AnnotationConfiguration.scanForAnnotations(AnnotationConfiguration.java:456)
	at org.eclipse.jetty.annotations.AnnotationConfiguration.configure(AnnotationConfiguration.java:365)
	at org.eclipse.jetty.webapp.WebAppContext.configure(WebAppContext.java:517)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1472)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:785)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:133)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:115)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:167)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:133)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:115)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:133)
	at org.eclipse.jetty.server.Server.start(Server.java:418)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:107)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:385)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.runner.Runner.run(Runner.java:530)
	at org.eclipse.jetty.runner.Runner.main(Runner.java:571)
Caused by: 
MultiException[java.lang.RuntimeException: Error scanning entry org/graphqlize/java/GraphQLResolver.class from jar file:///app/target/webapp/WEB-INF/lib/graphqlize-java-0.1.0-alpha20.jar, java.lang.RuntimeException: Error scanning entry org/graphqlize/java/GraphQLizeResolver.class from jar file:///app/target/webapp/WEB-INF/lib/graphqlize-java-0.1.0-alpha20.jar]
	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:872)
	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:839)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:161)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:468)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
	at java.lang.Thread.run(Thread.java:748)
Suppressed: 
	|java.lang.RuntimeException: Error scanning entry org/graphqlize/java/GraphQLizeResolver.class from jar file:///app/target/webapp/WEB-INF/lib/graphqlize-java-0.1.0-alpha20.jar
	|	at org.eclipse.jetty.annotations.AnnotationParser.lambda$parseJar$0(AnnotationParser.java:883)
	|	at java.util.TreeMap$ValueSpliterator.forEachRemaining(TreeMap.java:2897)
	|	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
	|	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:875)
	|	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:839)
	|	at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:161)
	|	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:468)
	|	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
	|	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
	|	at java.lang.Thread.run(Thread.java:748)
	|Caused by: 
	|java.lang.IllegalArgumentException
	|	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:160)
	|	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:143)
	|	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:418)
	|	at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:933)
	|	at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:918)
	|	at org.eclipse.jetty.annotations.AnnotationParser.lambda$parseJar$0(AnnotationParser.java:879)
	|	at java.util.TreeMap$ValueSpliterator.forEachRemaining(TreeMap.java:2897)
	|	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
	|	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:875)
	|	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:839)
	|	at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:161)
	|	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:468)
	|	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
	|	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
	|	at java.lang.Thread.run(Thread.java:748)
Caused by: 
java.lang.RuntimeException: Error scanning entry org/graphqlize/java/GraphQLResolver.class from jar file:///app/target/webapp/WEB-INF/lib/graphqlize-java-0.1.0-alpha20.jar
	at org.eclipse.jetty.annotations.AnnotationParser.lambda$parseJar$0(AnnotationParser.java:883)
	at java.util.TreeMap$ValueSpliterator.forEachRemaining(TreeMap.java:2897)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:875)
	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:839)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:161)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:468)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
	at java.lang.Thread.run(Thread.java:748)
Caused by: 
java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:160)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:143)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:418)
	at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:933)
	at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:918)
	at org.eclipse.jetty.annotations.AnnotationParser.lambda$parseJar$0(AnnotationParser.java:879)
	at java.util.TreeMap$ValueSpliterator.forEachRemaining(TreeMap.java:2897)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:875)
	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:839)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:161)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:468)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
	at java.lang.Thread.run(Thread.java:748)
2020-11-17 20:42:50.889:INFO:oejs.AbstractConnector:main: Started ServerConnector@2286778{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2020-11-17 20:42:50.892:INFO:oejs.Server:main: Started @2713ms
```

**Comment by tamizhvendan** [comment]
@odwrotnie Can you try with an older version, I guess it could be because of the latest release?

**Comment by odwrotnie** [comment]
I created my own example with Akka HTTP, do you think its good idea to include it in the repo?

**Comment by tamizhvendan** [comment]
Yeah, It'd be useful. Feel free to send the pull request
